package com.jccr.adminparro.pojo;
// Generated 13/03/2017 10:16:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name="admin"
    ,catalog="parroquia"
)
public class Admin  implements java.io.Serializable {


     private int CAdmin;
     private String nombre;
     private String usuario;
     private String passw;
     private int CLugar;
     private String descrip;

    public Admin() {
    }

	
    public Admin(int CAdmin, String nombre, String usuario, String passw, int CLugar) {
        this.CAdmin = CAdmin;
        this.nombre = nombre;
        this.usuario = usuario;
        this.passw = passw;
        this.CLugar = CLugar;
    }
    public Admin(int CAdmin, String nombre, String usuario, String passw, int CLugar, String descrip) {
       this.CAdmin = CAdmin;
       this.nombre = nombre;
       this.usuario = usuario;
       this.passw = passw;
       this.CLugar = CLugar;
       this.descrip = descrip;
    }
   
    @Id    
    @Column(name="c_admin", unique=true, nullable=false)
    public int getCAdmin() {
        return this.CAdmin;
    }
    
    public void setCAdmin(int CAdmin) {
        this.CAdmin = CAdmin;
    }

    
    @Column(name="Nombre", nullable=false, length=28)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="usuario", nullable=false, length=18)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="passw", nullable=false, length=18)
    public String getPassw() {
        return this.passw;
    }
    
    public void setPassw(String passw) {
        this.passw = passw;
    }

    
    @Column(name="c_lugar", nullable=false)
    public int getCLugar() {
        return this.CLugar;
    }
    
    public void setCLugar(int CLugar) {
        this.CLugar = CLugar;
    }

    
    @Column(name="Descrip", length=38)
    public String getDescrip() {
        return this.descrip;
    }
    
    public void setDescrip(String descrip) {
        this.descrip = descrip;
    }

}


