package com.jccr.adminparro.pojo;
// Generated 13/03/2017 10:16:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name="usuarios"
    ,catalog="parroquia"
)
public class Usuarios  implements java.io.Serializable {


     private int idUsuarios;
     private String nombre;
     private String passw;
     private String descripcion;

    public Usuarios() {
    }

	
    public Usuarios(int idUsuarios, String nombre, String passw) {
        this.idUsuarios = idUsuarios;
        this.nombre = nombre;
        this.passw = passw;
    }
    public Usuarios(int idUsuarios, String nombre, String passw, String descripcion) {
       this.idUsuarios = idUsuarios;
       this.nombre = nombre;
       this.passw = passw;
       this.descripcion = descripcion;
    }
   
    @Id     
    @Column(name="id_usuarios", unique=true, nullable=false)
    public int getIdUsuarios() {
        return this.idUsuarios;
    }
    
    public void setIdUsuarios(int idUsuarios) {
        this.idUsuarios = idUsuarios;
    }

    
    @Column(name="nombre", nullable=false, length=18)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="passw", nullable=false, length=18)
    public String getPassw() {
        return this.passw;
    }
    
    public void setPassw(String passw) {
        this.passw = passw;
    }

    
    @Column(name="descripcion", length=32)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

}


